service: logging

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  role: arn:aws:iam::139333950783:role/myapp-logging-role

functions:
  dispatchErrors:
    handler: handler.dispatchErrors
    events:
      - sns: arn:aws:sns:eu-central-1:139333950783:PRODUCTION_ERRORS
