service: notes

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  environment:
    APP_NAME: Prod logs
    APP_STAGE: ${opt:stage,self:provider.stage}
    SERVICE_NAME: Notes Service

functions:
  createNotes:
    handler: handler.createNotes
    events:
      - http:
          path: notes
          method: post

  getNoteById:
    handler: handler.getNotesById
    events:
      - http:
          path: notes/{id}
          method: get
